Repository armory-io/armory-stack, pull requests merged in 2025-01, with the labels that each got.

#4251 chore(cd): update clouddriver-armory version to 2025.01.03.20.58.36.release-2.35.x
  stack.yml
Labels: autoMerge, stackUpdate, clouddriver-armory

#4273 chore(cd): update kayenta-armory version to 2025.01.23.21.26.00.release-2.35.x
  stack.yml
Labels: autoMerge, stackUpdate, kayenta-armory

#4274 chore(cd): update deck-armory version to 2025.01.28.05.44.06.master
  stack.yml
Labels: autoMerge, stackUpdate, deck-armory

#4277 chore(cd): update echo-armory version to 2025.01.28.17.33.17.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, echo-armory

#4278 chore(cd): update front50-armory version to 2025.01.28.17.34.16.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, front50-armory

#4281 chore(cd): update rosco-armory version to 2025.01.28.17.35.23.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, rosco-armory

#4265 chore(cd): update deck-armory version to 2025.01.21.17.32.41.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, deck-armory

#4279 chore(cd): update orca-armory version to 2025.01.28.17.37.57.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, orca-armory

#4280 chore(cd): update igor-armory version to 2025.01.28.17.34.58.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, igor-armory

#4284 chore(cd): update kayenta-armory version to 2025.01.29.17.30.22.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, kayenta-armory

#4287 chore(cd): update fiat-armory version to 2025.01.29.19.24.31.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, fiat-armory

#4286 chore(cd): update clouddriver-armory version to 2025.01.28.17.36.23.release-2.36.x
  stack.yml
Labels: autoMerge, clouddriver-armory

#4289 chore(cd): update deck-armory version to 2025.01.29.23.53.48.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, deck-armory

#4290 chore(cd): update clouddriver-armory version to 2025.01.30.00.03.22.release-2.36.x
  stack.yml
Labels: autoMerge, stackUpdate, clouddriver-armory
